name: "OpenBSD build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v6

    - name: Test on OpenBSD 7.9
      uses: cross-platform-actions/action@v1.2.0  # see https://github.com/cross-platform-actions/action
      with:
        operating_system: openbsd
        version: '7.9'
        shell: bash
        run: |
          uname -a
          whoami
          pwd
          # http://ftp.openbsd.org/pub/OpenBSD/7.9/packages/amd64/
          sudo pkg_add gcc g++ automake autoconf autoconf-archive libtool cppunit
          export CXX=eg++
          eg++ --version
          autoreconf -v --install --force
          ./configure --prefix=/usr
          CPU_COUNT="$( ( ( getconf _NPROCESSORS_ONLN 2>/dev/null || (getconf NPROCESSORS_ONLN 2>/dev/null) ) || nprocx 2>/dev/null ) || echo "1")"
          JOBS="$(( $((CPU_COUNT / 2)) > 1 ? $((CPU_COUNT / 2)) : 1 ))"
          make -j$JOBS

